// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:mamago/common/enums.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'home_state.freezed.dart';

@freezed
class HomeState with _$HomeState {
  const factory HomeState({
    @Default(ConvertingLanguage.korean) ConvertingLanguage language,
    @Default(true) isLeft,
  }) = _HomeState;
}
