// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:mamago/common/enums.dart';
import 'package:mamago/data/translated_item_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'translate_state.freezed.dart';

@freezed
class TranslateState with _$TranslateState {
  const factory TranslateState({
    @Default(ConvertingLanguage.korean) ConvertingLanguage language,
    @Default(ToneAndManner.business) ToneAndManner toneAndManner,
    String? nativeText,
    @Default([]) List<TranslateItem> convertedText,

  }) = _TranslateState;
}
